import { Preferences } from "@/types";

// src/constants/index.ts
type ColumnEntry = { active: boolean; order: number };

const columnsActive = {
	name: { active: true },
	size: { active: false },
	state: { active: true },
	progress: { active: true },
	eta: { active: false },
	dlspeed: { active: true },
	upspeed: { active: true },
	ratio: { active: false },
	num_seeds: { active: true },
	num_leechs: { active: true },
	added_on: { active: true },
	uploaded: { active: false },
	uploaded_session: { active: false },
	category: { active: false },
	tracker: { active: false },
} as const;

const columns = Object.keys(columnsActive).reduce(
	(acc, key, idx) => {
		const k = key as keyof typeof columnsActive;
		acc[k] = {
			active: columnsActive[k].active,
			order: idx + 1,
		};
		return acc;
	},
	{} as Record<keyof typeof columnsActive, ColumnEntry>,
);

export const defaultPreferences = {
	locale: "en",
	save_path: "",
	temp_path: "",
	temp_path_enabled: false,
	create_subfolder_enabled: true,
	start_paused_enabled: false,
	auto_tmm_enabled: false,
	queueing_enabled: false,
	max_active_downloads: 3,
	max_active_torrents: 5,
	max_active_uploads: 3,
	dl_limit: 0,
	up_limit: 0,
	alt_dl_limit: 1024,
	alt_up_limit: 1024,
	listen_port: 6881,
	upnp: true,
	random_port: false,
	dht: true,
	pex: true,
	lsd: true,
	encryption: 0,
	columns,
	sizeUnit: "B",
};

export const columnsDictionary: Record<keyof typeof columns, string> = {
	name: "Name",
	state: "State",
	progress: "Progress",
	dlspeed: "Download Speed",
	upspeed: "Upload Speed",
	ratio: "Ratio",
	num_seeds: "Seeds",
	num_leechs: "Leeches",
	size: "Size",
	added_on: "Added On",
	uploaded: "Total Uploaded",
	uploaded_session: "Uploaded Session",
	eta: "ETA",
	category: "Category",
	tracker: "Tracker",
};

export const qbittorrentLocales: Record<string, string> = {
  af: "Afrikaans",
  ar: "العربية (Arabic)",
  az: "Azərbaycan dili (Azerbaijani)",
  be: "Беларуская (Belarusian)",
  bg: "Български (Bulgarian)",
  bn: "বাংলা (Bengali)",
  br: "Brezhoneg (Breton)",
  bs: "Bosanski (Bosnian)",
  ca: "Català (Catalan)",
  cs: "Čeština (Czech)",
  cy: "Cymraeg (Welsh)",
  da: "Dansk (Danish)",
  de: "Deutsch (German)",
  el: "Ελληνικά (Greek)",
  en: "English",
  en_AU: "English (Australia)",
  en_GB: "English (United Kingdom)",
  eo: "Esperanto",
  es: "Español (Spanish)",
  et: "Eesti (Estonian)",
  eu: "Euskara (Basque)",
  fa: "فارسی (Persian)",
  fi: "Suomi (Finnish)",
  fr: "Français (French)",
  gl: "Galego (Galician)",
  he: "עברית (Hebrew)",
  hi: "हिन्दी (Hindi)",
  hr: "Hrvatski (Croatian)",
  hu: "Magyar (Hungarian)",
  ia: "Interlingua",
  id: "Bahasa Indonesia (Indonesian)",
  is: "Íslenska (Icelandic)",
  it: "Italiano (Italian)",
  ja: "日本語 (Japanese)",
  ka: "ქართული (Georgian)",
  kk: "Қазақ тілі (Kazakh)",
  ko: "한국어 (Korean)",
  ky: "Кыргызча (Kyrgyz)",
  lt: "Lietuvių (Lithuanian)",
  lv: "Latviešu (Latvian)",
  mk: "Македонски (Macedonian)",
  mn: "Монгол (Mongolian)",
  mr: "मराठी (Marathi)",
  ms: "Bahasa Melayu (Malay)",
  nb: "Norsk Bokmål (Norwegian Bokmål)",
  nl: "Nederlands (Dutch)",
  nn: "Norsk Nynorsk (Norwegian Nynorsk)",
  oc: "Occitan",
  pl: "Polski (Polish)",
  pt: "Português (Portuguese)",
  pt_BR: "Português do Brasil (Portuguese, Brazil)",
  ro: "Română (Romanian)",
  ru: "Русский (Russian)",
  sk: "Slovenčina (Slovak)",
  sl: "Slovenščina (Slovenian)",
  sq: "Shqip (Albanian)",
  sr: "Српски (Serbian)",
  sv: "Svenska (Swedish)",
  ta: "தமிழ் (Tamil)",
  te: "తెలుగు (Telugu)",
  th: "ไทย (Thai)",
  tr: "Türkçe (Turkish)",
  uk: "Українська (Ukrainian)",
  uz: "Oʻzbekcha (Uzbek)",
  vi: "Tiếng Việt (Vietnamese)",
  zh_CN: "简体中文 (Chinese, Simplified)",
  zh_HK: "繁體中文（香港） (Chinese, Hong Kong)",
  zh_TW: "繁體中文（台灣） (Chinese, Traditional)",
};